# Generated by Django 6.0.4 on 2026-04-07 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('late_birth_certificate', 'Late Birth Certificate'), ('change_of_particulars', 'Change of Particulars')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecitizen_application_ref', models.CharField(max_length=100, unique=True)),
                ('document_status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('incomplete', 'Incomplete')], default='pending', max_length=20)),
                ('processing_status', models.CharField(choices=[('not_started', 'Not Started'), ('under_review', 'Under Review'), ('processed', 'Processed')], default='not_started', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.applicantprofile')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='queueing.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huduma_booking_ref', models.CharField(max_length=100, unique=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('booking_status', models.CharField(choices=[('booked', 'Booked'), ('attended', 'Attended'), ('missed', 'Missed')], default='booked', max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.applicantprofile')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='queueing.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('current_status', models.CharField(choices=[('tracking', 'Tracking'), ('waiting', 'Waiting'), ('called', 'Called'), ('in_service', 'In Service'), ('completed', 'Completed'), ('missed', 'Missed')], default='tracking', max_length=20)),
                ('arrival_confirmed', models.BooleanField(default=False)),
                ('joined_queue_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_wait_minutes', models.PositiveIntegerField(default=0)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tickets', to='accounts.applicantprofile')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tickets', to='queueing.application')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_ticket', to='queueing.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='QueueStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.serviceofficer')),
                ('queue_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='queueing.queueticket')),
            ],
        ),
    ]
