# Generated by Django 6.0.4 on 2026-04-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='amendment_name_of_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='amendment_name_of_father',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='amendment_name_of_mother',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='amendment_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='amendment_place_of_birth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='application_title',
            field=models.CharField(default='Application for Current Birth Certificate', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='born_in_health_facility',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='child_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='child_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='child_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='child_over_18',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='county_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='father_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='father_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='notification_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='residential_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='type_of_application',
            field=models.CharField(blank=True, choices=[('without_amendment', 'Application for Birth Certificate without Amendment'), ('with_amendment', 'Application for Birth Certificate with Amendment')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='upload_applicant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='upload_birth_notification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='upload_parent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='document_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('incomplete', 'Incomplete'), ('verified', 'Verified')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='ecitizen_application_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('processed', 'Processed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(choices=[('birth_certificate', 'Birth Certificate')], max_length=100, unique=True),
        ),
    ]
