# Generated by Django 6.0.4 on 2026-04-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0002_application_amendment_name_of_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='upload_applicant_id',
            field=models.FileField(blank=True, null=True, upload_to='uploads/applicant_ids/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='upload_birth_notification',
            field=models.FileField(blank=True, null=True, upload_to='uploads/birth_notifications/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='upload_parent_id',
            field=models.FileField(blank=True, null=True, upload_to='uploads/parent_ids/'),
        ),
    ]
