# Generated by Django 6.0.4 on 2026-04-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0003_alter_application_upload_applicant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
