# Generated by Django 6.0.4 on 2026-06-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueticket',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queueticket',
            name='skipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queueticket',
            name='current_status',
            field=models.CharField(choices=[('tracking', 'Tracking'), ('waiting', 'Waiting'), ('called', 'Called'), ('in_service', 'In Service'), ('completed', 'Completed'), ('missed', 'Missed'), ('skipped', 'Skipped / No Response')], default='tracking', max_length=20),
        ),
    ]
