# Generated by Django 6.0.4 on 2026-06-29 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('queueing', '0006_queueticket_called_at_queueticket_skipped_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_feedbacks', to='accounts.applicantprofile')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queueing.application')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queueing.appointment')),
                ('queue_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='queueing.queueticket')),
            ],
        ),
    ]
